name: Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: php-actions/composer@v1

    - name: Validate PHP
      run: |
        composer validate
        composer install --prefer-dist --no-progress --no-suggest
        composer lint:wpcs
